### ISSUE TITLE
Tries to do a get on the endpoint

### ISSUE THREAD

**Issue by dutchiexl** [1up-lab/OneupUploaderBundle#128]
I installed Oneuploader with blueimp, but when I render the page, it tries to do a get on the data url which gives a : 405 (Method Not Allowed) POST only jquery error.

**Comment by markidm** [comment]
What was the solution here?

**Comment by antongorodezkiy** [comment]
I've faced the same issue. @dutchiexl @markidm did you find any solution for this?

**Comment by antongorodezkiy** [comment]
Seems like the same issue #173 I still have no ideas

**Comment by antongorodezkiy** [comment]
Found the issue and it's not in the library of course. In my case the issue was in the Apache's ModSecurity module's `SecRequestBodyLimit` setting. And Apache logged the following error:

`... ModSecurity: Request body (Content-Length) is larger than the configured limit (10485760). ... [uri "/_uploader/flipbook/upload"]`

**Comment by markidm** [comment]
I don't even know what I was working on when I asked the question! Well done for sorting it @antongorodezkiy
