### ISSUE TITLE
Default storage directory open to incorrect implementation and/or abuse

### ISSUE THREAD

**Issue by MadmanMonty** [1up-lab/OneupUploaderBundle#166]
More of a recommendation than an issue. 

The current default behaviour uses the web/uploads folder as the storage location. The result being all files uploaded are open to the web, unless deleted (moved) to a secure location by the developer.

I can foresee users wanting to make uploaded files available to all, but suspect it might be better to use a safer storage location by default, perhaps the example you have in the config tests might be a more prudent default:

```
storage:
              directory: %kernel.root_dir%/cache/%kernel.environment%/upload
```

**Comment by giosh94mhz** [comment]
@MadmanMonty Premise: I'm not a UploaderBundle maintainer, so this is just my opinion.

Saving to cache dir is not a good idea, since the cache can be cleared or moved (e.g. during deployment of a new revision) during the upload; if you do so, the user upload can be lost -- in case of monolithic upload --, or corrupted -- in case of chunked upload. Also the `web/uploads` folder is a de-facto standard AFAIK for symfony (or maybe just capistrano/capifony).

If using endpoint names and not so thousands of files, the current implementation is enough and the developer can just put an .htaccess into the target folder.

Of course, having it public is not the best, so I think that at least the filename shoul have more entropy by changing `UniqidNamer::name` to:
```php
public function name(FileInterface $file)
{
    return sprintf('%s.%s', uniqid(null, true), $file->getExtension());
}
```
