### ISSUE TITLE
Limit the number of file

### ISSUE THREAD

**Issue by jokari4242** [1up-lab/OneupUploaderBundle#231]
Hi;

Thanks for this nice bundle;

How can i limit the number of total file submited? I'm using dropzone.

Thanks for your help;

Antoine

**Comment by JHGitty** [comment]
1. Be sure that you are able to show an user-friendly error if the number of total files has been reached. This bundle has support for error messages. Dropzone is supported: https://github.com/1up-lab/OneupUploaderBundle/blob/master/Uploader/ErrorHandler/DropzoneErrorHandler.php

2. You are able to send an error message from the server once the total file number has been reached. I think you should use the validation feature: https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/custom_validator.md

So you just need to think about how to save the number of total files. The validation code just needs to check it. Because you have access to the ``request`` on the validation code you are also able to passthrough own information about the current upload scenario.
