### ISSUE TITLE
FileSystemFile breaks with symfony/http-foundation ^5.0

### ISSUE THREAD

**Issue by ricohumme** [1up-lab/OneupUploaderBundle#368]
Hi,

Just ran into this issue. There is no requirement for this dependency in the composer file, so my project updated this dependency to 5.0.

In the FileSystemFile the UploadedFile class no longer has getClientSize, and probably more methods are failing due to 5.0

Could a requirement of http-foundation be made in the composer.json ?
Or is there another way to resolve this?

**Comment by ricohumme** [comment]
Hi,

It's been a month. Any thoughts on this?

**Comment by steveWinter** [comment]
As of yesterday I'm working on updates for SF 5.0 in https://github.com/steveWinter/OneupUploaderBundle had to solve a number of issues with 4.4 first, now working to get tests passing for 5.0 but particularly because of changes to the functional testing in SF 5.0 it's 'non-trivial', particularly when trying to maintinan BC to 3.4

**Comment by bytehead** [comment]
@ricohumme there is another issue which covers this topic: #364. I'll close this in favor of the older one :)
